# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20170704_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='categories',
        ),
    ]
